# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{aozora4reader}
  s.version = "1.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = [%q{takahashim}]
  s.date = %q{2011-09-07}
  s.description = %q{Aozora Bunko converter for Sony Reader}
  s.email = %q{maki@rubycolor.org}
  s.executables = [%q{a4r}]
  s.extra_rdoc_files = [
    "ChangeLog",
    "LICENSE",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    "ChangeLog",
    "LICENSE",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "aozora4reader.gemspec",
    "bin/a4r",
    "data/gaiji.txt",
    "data/gaiji2.txt",
    "lib/aozora4reader.rb",
    "memo.txt",
    "sty/aozora.sty",
    "sty/aozora4reader.sty",
    "sty/aozorakindle.sty",
    "test/helper.rb",
    "test/test_aozora4reader.rb"
  ]
  s.homepage = %q{http://github.com/takahashim/aozora4reader}
  s.require_paths = [%q{lib}]
  s.rubygems_version = %q{1.8.6}
  s.summary = %q{Aozora Bunko converter for Sony Reader}

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_development_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    else
      s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
    end
  else
    s.add_dependency(%q<thoughtbot-shoulda>, [">= 0"])
  end
end

